// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only supported for Android and iOS platforms.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoz7W655dwOjAayTyR5FgjMLvXLBnA98',
    appId: '1:764096540833:android:ca7c46b008cac4e7f2c0e0',
    messagingSenderId: '764096540833',
    projectId: 'app-donut',
    storageBucket: 'app-donut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZM02Tx1iaKg7cN-0f5BKOXs2kSRCa6Y',
    appId: '1:764096540833:ios:58f97a0ff7decbe4f2c0e0',
    messagingSenderId: '764096540833',
    projectId: 'app-donut',
    storageBucket: 'app-donut.firebasestorage.app',
    iosBundleId: 'com.example.questForKids',
  );
}

